# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 413366faa6980cc58d82e8f72b364b757fef56ae8ab56fb312f8d21002ce0bd3bb2ddad210f59a1134a7123c631f5b84d735167ab2f87cfbf5d7ebbe5a57da7c

test:
  secret_key_base: e0bd7a56908c10f1737c4ecd7bff53f8a2c30104681ae6314691f62679cb09e23753b34bbfa0a8da6052616d52e5cba26a515aef19dd5a1cbfcc6779e1cddeab

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
